# Generates a C source that embeds a single self-contained HTML bundle as a
# byte array, so the application ships as one executable with no loose files.
#
# Picks frontend/dist/index.html when present, otherwise frontend/placeholder.html
# — this lets a pure-C build (without the frontend toolchain) still compile. For
# release builds, build the frontend first (`pnpm --dir frontend build`) so the
# real bundle is embedded. Regenerated on each CMake (re)configure.
function(quaero_generate_embedded_html output_file symbol)
  set(dist "${CMAKE_SOURCE_DIR}/frontend/dist/index.html")
  set(placeholder "${CMAKE_SOURCE_DIR}/frontend/placeholder.html")
  if(EXISTS "${dist}")
    set(input "${dist}")
  else()
    set(input "${placeholder}")
  endif()

  file(READ "${input}" hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," body "${hex}")

  file(WRITE "${output_file}"
    "/* Auto-generated by cmake/EmbedAssets.cmake. Do not edit.\n"
    "   Source: ${input} */\n"
    "#include <stddef.h>\n"
    "\n"
    "const unsigned char ${symbol}[] = { ${body} 0x00 };\n"
    "const size_t ${symbol}_len = sizeof(${symbol}) - 1u;\n")

  message(STATUS "Embedded frontend bundle from: ${input}")
endfunction()
